### PR TITLE
Fix atomicAdd on minGW compiler

### PR DESCRIPTION
**Pull request by jpcima**
It would not build on MinGW-w64 GCC 9.2.1.

The error was:

```
/home/jpc/documents/projects/sfizz/vst/external/VST_SDK/VST3_SDK/pluginterfaces/base/funknown.cpp: In function 'Steinberg::int32 Steinberg::FUnknownPrivate::atomicAdd(Steinberg::int32&, Steinberg::int32)':
/home/jpc/documents/projects/sfizz/vst/external/VST_SDK/VST3_SDK/pluginterfaces/base/funknown.cpp:87:40: error: no matching function for call to '_InterlockedExchangeAdd(Steinberg::int32*, Steinberg::int32&)'
   87 |  return InterlockedExchangeAdd (&var, d) + d;
```

### CODE REVIEW

File: base/funknown.cpp [hunk 1]
```diff
@@ -84,7 +84,7 @@ namespace FUnknownPrivate {
 int32 PLUGIN_API atomicAdd (int32& var, int32 d)
 {
 #if SMTG_OS_WINDOWS
-	return InterlockedExchangeAdd (&var, d) + d;
+	return InterlockedExchangeAdd ((LONG*)&var, d) + d;
```
Comment (abique) [inline base/funknown.cpp:87]: I disagree with that.
Use atomic from the c++ standard library.

**Review by abique — CHANGES_REQUESTED** [review]

File: base/funknown.cpp (hunk 1 above)
Comment (jpcima) [reply base/funknown.cpp:87]: When trying to include `<stdatomic.h>` as do Android and Mac, it complains about `_Atomic` not defined. Including `<atomic>` worked fine though.
Do you suggest that I cast it into a `std::atomic<int32>*` ?

Comment (abique) [reply base/funknown.cpp:87]: No, I suggest to rewrite it all to use std::atomic<int> instead.
Cast are absolutely not needed here.
But check with the Steinberg guys what to do, I am not working at Steinberg.
